name: Phoenix Inwarranty Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '30 02 * * *'
    - cron: '00 14 * * *'

jobs:  
  run-tests: 
    runs-on: github-runner-ec2-demo

    steps:

      - name: checkout the code
        uses: actions/checkout@v6.0.1
    
      - name: install node js and npm 
        uses: actions/setup-node@v6.1.0
        with:
          node-version: "22"
          check-latest: false
          cache: npm

      - name: install newman and htmlextra  
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: run collection
        run: |
            newman run 'In Warranty Flow latest.postman_collection.json' \
            -e QA.postman_environment.json \
            -d testdata.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: newman report
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with:
          name: newman report
          path: ./newman/*.html
      
      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          publish_dir: newman/

      - name: email notification
        if: always()
        uses: dawidd6/action-send-mail@v7
        with: 
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix Inwarranty Flow Test Execution Notification 
          to: bhattacharya.aishik24@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hi,
                Phoenix inwarranty flow has been executed. The report has been published and the url 
                is: https://aishikb24.github.io/Phoenix-Inwarranty-Flow-Demo/

                
                
          
            
          
          
          
          
          
          
        
      
      
    
    
      
    
         
    
      
    
    
    
    
      


  
    
    
